
name: Go-CI

on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.13', '1.12', '1.14'  ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: |
        go test -race -run TestConcurrent*
        go build -tags appengine
        go test -tags appengine
        go test -v
        go test -v ./roaring64
        go test -v ./BitSliceIndexing
        GOARCH=386 go build
        GOARCH=arm go build
        GOARCH=arm64 go build
        GOARCH=386 go build ./roaring64
        GOARCH=arm go build ./roaring64
        GOARCH=arm64 go build ./roaring64
        GOARCH=386 go build ./BitSliceIndexing
        GOARCH=arm go build ./BitSliceIndexing
        GOARCH=arm64 go build ./BitSliceIndexing
        GOARCH=386 go test -v 
        GOARCH=386 go test -v ./roaring64
        GOARCH=386 go test -v ./BitSliceIndexing
