
name: Go-CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go test -race -run TestConcurrent*
        go build -tags appengine
        go test -tags appengine
        go test -v
        go test -v ./roaring64
        go test -v ./BitSliceIndexing
        GOARCH=386 go build
        GOARCH=arm go build
        GOARCH=arm64 go build
        GOARCH=386 go build ./roaring64
        GOARCH=arm go build ./roaring64
        GOARCH=arm64 go build ./roaring64
        GOARCH=386 go build ./BitSliceIndexing
        GOARCH=arm go build ./BitSliceIndexing
        GOARCH=arm64 go build ./BitSliceIndexing
        GOARCH=386 go test -v 
        GOARCH=386 go test -v ./roaring64
        GOARCH=386 go test -v ./BitSliceIndexing
